# Generated by Django 6.0 on 2026-01-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'טיוטה'), ('invoiced', 'בקשה לתשלום'), ('paid', 'שולם')], default='draft', max_length=10)),
                ('sumit_invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sumit_recipt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sumit_invoice_link', models.CharField(blank=True, max_length=255, null=True)),
                ('sumit_recipt_link', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('recipt_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.service')),
            ],
            options={
                'verbose_name': 'תשלום',
                'verbose_name_plural': 'תשלומים',
                'ordering': ['-created_at'],
            },
        ),
    ]
