# Generated by Django 6.0 on 2026-01-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('draft', 'טיוטה'), ('billed', 'חוייב'), ('paid', 'שולם')], default='draft', max_length=10),
        ),
    ]
