# Generated by Django 6.0 on 2026-02-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
