# Generated by Django 6.0 on 2026-01-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_type', models.CharField(choices=[('normal', 'רגיל'), ('accounting', 'חשבונות')], default='normaml', max_length=30, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('is_alerts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='customers.customer')),
            ],
            options={
                'verbose_name': 'איש קשר',
                'verbose_name_plural': 'אנשי קשר',
            },
        ),
    ]
