# Generated by Django 6.0 on 2026-01-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumit',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workdrive',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
