# Generated by Django 6.0 on 2026-01-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_sumit_is_connected_workdrive_is_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumit',
            name='customer_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workdrive',
            name='customer_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workdrive',
            name='project_folder',
            field=models.BooleanField(default=False),
        ),
    ]
