# Generated by Django 6.0 on 2026-01-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudget',
            name='name',
            field=models.CharField(default='תקציב פרויקט', max_length=255),
            preserve_default=False,
        ),
    ]
