# Generated by Django 6.0 on 2026-01-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectbudget_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbudget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
