# Generated by Django 6.0 on 2026-01-11 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'טיוטה'), ('billed', 'חוייב'), ('paid', 'שולם')], default='draft', max_length=30)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('sumit_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sumit_invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sumit_invoice_download_url', models.CharField(blank=True, null=True, verbose_name=255)),
                ('sumit_recipt_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sumit_recipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sumit_recipt_download_url', models.CharField(blank=True, null=True, verbose_name=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'תשלום',
                'verbose_name_plural': 'תשלומים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 11, 9, 12, 54, 813350, tzinfo=datetime.timezone.utc)),
        ),
    ]
