# Generated by Django 6.0 on 2026-01-11 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_payment_alter_timesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='sumit_invoice_download_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sumit_recipt_download_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 11, 9, 34, 4, 473032, tzinfo=datetime.timezone.utc)),
        ),
    ]
