# Generated by Django 6.0 on 2026-01-11 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_payment_sumit_invoice_download_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 11, 10, 19, 50, 273764, tzinfo=datetime.timezone.utc)),
        ),
    ]
