# Generated by Django 6.0 on 2026-01-11 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_alter_timesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 11, 10, 22, 57, 985311, tzinfo=datetime.timezone.utc)),
        ),
    ]
