# Generated by Django 6.0 on 2026-01-11 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_alter_timesheet_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 11, 10, 37, 45, 966979, tzinfo=datetime.timezone.utc)),
        ),
    ]
