# Generated by Django 6.0 on 2026-01-11 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_delete_payment_alter_timesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 11, 10, 40, 52, 927942, tzinfo=datetime.timezone.utc)),
        ),
    ]
