# Generated by Django 6.0 on 2026-01-11 11:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_timesheet_date'),
        ('projects', '0003_projectbudget_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='projects.projectbudget'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 11, 11, 18, 37, 576530, tzinfo=datetime.timezone.utc)),
        ),
    ]
