# Generated by Django 6.0 on 2026-01-13 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_timesheet_budget_alter_timesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 13, 10, 12, 20, 263244, tzinfo=datetime.timezone.utc)),
        ),
    ]
