# Generated by Django 6.0 on 2026-01-21 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_timesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 21, 14, 40, 3, 747471, tzinfo=datetime.timezone.utc)),
        ),
    ]
