# Generated by Django 6.0 on 2026-01-25 08:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_alter_timesheet_date'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 25, 8, 33, 18, 93494, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.datetime(2026, 1, 25, 8, 33, 18, 93810, tzinfo=datetime.timezone.utc))),
                ('start_time', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=0, max_digits=2)),
                ('is_online', models.BooleanField(default=False)),
                ('online_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'פגישה',
                'verbose_name_plural': 'פגישות',
                'ordering': ['-created_at'],
            },
        ),
    ]
