# Generated by Django 6.0 on 2026-01-25 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_alter_timesheet_date_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 25, 8, 45, 53, 186132, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 25, 8, 45, 53, 185845, tzinfo=datetime.timezone.utc)),
        ),
    ]
