# Generated by Django 6.0 on 2026-01-25 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_alter_meeting_date_alter_timesheet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין'), ('completed', 'הושלם'), ('canceled', 'בוטל')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 25, 8, 52, 20, 89319, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 25, 8, 52, 20, 89011, tzinfo=datetime.timezone.utc)),
        ),
    ]
