# Generated by Django 6.0 on 2026-01-26 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_alter_meeting_date_alter_timesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 26, 7, 41, 41, 808773, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 26, 7, 41, 41, 808469, tzinfo=datetime.timezone.utc)),
        ),
    ]
