# Generated by Django 6.0 on 2026-01-26 08:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_alter_meeting_date_alter_timesheet_date'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 26, 8, 16, 57, 798763, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 1, 26, 8, 16, 57, 798471, tzinfo=datetime.timezone.utc)),
        ),
    ]
