# Generated by Django 6.0 on 2026-02-03 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_meeting_customer_alter_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 3, 8, 15, 36, 903695, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 3, 8, 15, 36, 903391, tzinfo=datetime.timezone.utc)),
        ),
    ]
