# Generated by Django 6.0 on 2026-02-09 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0020_alter_meeting_date_alter_timesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 9, 9, 52, 32, 588779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 9, 9, 52, 32, 588476, tzinfo=datetime.timezone.utc)),
        ),
    ]
