# Generated by Django 6.0 on 2026-02-16 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_alter_meeting_date_alter_timesheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 16, 19, 49, 16, 583228, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 16, 19, 49, 16, 582779, tzinfo=datetime.timezone.utc)),
        ),
    ]
