# Generated by Django 6.0 on 2026-01-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_id', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='customer_logos/')),
                ('sumit_id', models.CharField(blank=True, max_length=30, null=True)),
                ('folder_id', models.CharField(blank=True, max_length=100, null=True)),
                ('folder_link', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadsource')),
            ],
            options={
                'verbose_name': 'לקוח',
                'verbose_name_plural': 'לקוחות',
            },
        ),
    ]
