# Generated by Django 6.0 on 2026-01-21 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'סוג התראה',
                'verbose_name_plural': 'סוגי התראה',
            },
        ),
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_email', models.BooleanField(default=False)),
                ('updated_email', models.BooleanField(default=False)),
                ('deleted_email', models.BooleanField(default=False)),
                ('created_in_app', models.BooleanField(default=False)),
                ('updated_in_app', models.BooleanField(default=False)),
                ('deleted_in_app', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('alert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alerttype')),
            ],
            options={
                'verbose_name': 'הגדרות התראות',
                'verbose_name_plural': 'הגדרות התראות',
                'unique_together': {('user', 'alert_type')},
            },
        ),
    ]
