# Generated by Django 6.0 on 2026-01-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'טיוטה'), ('lost', 'אבודה'), ('won', 'מאושרת'), ('sent', 'נשלחה')], default='draft', max_length=30)),
                ('object_id', models.PositiveBigIntegerField()),
                ('folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('folder_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'הצעת מחיר',
                'verbose_name_plural': 'הצעות מחיר',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_services', to='quotes.quote')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.service')),
            ],
            options={
                'verbose_name': 'שירות הצעת מחיר',
                'verbose_name_plural': 'שירותי הצעת מחיר',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_payments', to='quotes.quote')),
                ('quote_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='quotes.quote_service')),
            ],
            options={
                'verbose_name': 'תשלום הצעת מחיר',
                'verbose_name_plural': 'תשלומי הצעת מחיר',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['content_type', 'object_id'], name='quotes_quot_content_c3e13f_idx'),
        ),
    ]
