# Generated by Django 6.0 on 2026-02-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'טיוטה'), ('sent', 'נשלחה'), ('lost', 'אבודה'), ('won', 'מאושרת')], default='draft', max_length=30),
        ),
    ]
